#!/usr/bin/env node
// Writes the festival status table in docs/qa/INSTINCT-QUEUE.md from
// FESTIVALS_REGISTRY + _DATA_SETS, between the festival-status markers:
//
//     node scripts/festival-status.mjs           # rewrite the block
//     node scripts/festival-status.mjs --check   # exit 1 if it is stale (verify runs this)
//
// Why generated: the queue said "9 live" while the registry had 12, because
// the count was typed by hand and every flip left it behind. Now a flip that
// does not regenerate the table fails verify.

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadRegistry } from './lib/load-registry.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOC = path.join(root, 'docs', 'qa', 'INSTINCT-QUEUE.md');
const BEGIN = '<!-- festival-status:begin (generated by scripts/festival-status.mjs; do not hand-edit) -->';
const END = '<!-- festival-status:end -->';
const CHECK = process.argv.includes('--check');

const { REG, DS, scheduleActs, festivalEssentials, entryAgeLabel, campingLabel } = loadRegistry(root);

const rows = REG.map(e => {
  const c = e.config;
  const acts = scheduleActs(DS[c.id]?.artists);
  return {
    id: c.id, name: c.name, dates: c.dates || '', live: !!e.available,
    start: Number.isFinite(c.startMs) ? c.startMs : Infinity,
    acts: acts.length,
    timed: acts.filter(a => a.start).length,
    noStage: acts.filter(a => a.stage == null || a.stage === 'tba').length,
    stages: (DS[c.id]?.stages || []).length,
    hasData: !!DS[c.id],
  };
}).sort((a, b) => a.start - b.start || a.name.localeCompare(b.name));

const live = rows.filter(r => r.live), gated = rows.filter(r => !r.live);
const needs = r => !r.hasData ? 'page only (no data set)'
  : r.acts === 0 ? 'lineup'
  : r.timed === r.acts ? 'timed; flip gate'
  : r.noStage ? 'stage and time' : 'times';
const table = (list, last) => [
  `| Festival | Id | Dates | Acts | Timed | No stage | Stages | ${last} |`,
  '|---|---|---|---|---|---|---|---|',
  ...list.map(r => `| ${r.name} | \`${r.id}\` | ${r.dates} | ${r.acts} | ${r.timed} | ${r.noStage} | ${r.stages} | ${last === 'Needs' ? needs(r) : 'live'} |`),
];

const block = [
  BEGIN,
  `**${rows.length} registry entries: ${live.length} live, ${gated.length} gated.** Counted from`,
  '`FESTIVALS_REGISTRY` (live = `available: true`); acts, timed and no-stage rows',
  'from `_DATA_SETS`. Ordered by start date; entries without one sort last.',
  '',
  `**Gated (${gated.length})**`,
  '',
  ...table(gated, 'Needs'),
  '',
  `**Live (${live.length})**`,
  '',
  ...table(live, 'Status'),
  '',
  ...essentialsBlock(),
  END,
].join('\n');

// Festival essentials: the same config fields the app and /f/ pages read
// through festivalEssentials(). Recorded values only, never today's date, so
// this table cannot drift on its own; "unknown" is a real state, not a gap.
function essentialsBlock() {
  const ess = REG.map(e => {
    const c = e.config, f = festivalEssentials(c, 0), t = c.essentialsSources && c.essentialsSources.tickets;
    return { name: c.name, id: c.id, start: Number.isFinite(c.startMs) ? c.startMs : Infinity,
      age: entryAgeLabel(f.entryAge) || 'unknown', camp: f.camping == null ? 'unknown' : f.camping ? 'yes' : 'no',
      tix: t ? `${t.state} (checked ${t.observedAt})` : 'unknown' };
  }).sort((a, b) => a.start - b.start || a.name.localeCompare(b.name));
  const n = (k) => ess.filter(r => r[k] !== 'unknown').length;
  return [
    `**Festival essentials: entry age ${n('age')}/${ess.length} verified · camping ${n('camp')}/${ess.length} · official ticket state ${n('tix')}/${ess.length}.**`,
    'First-party, per edition (`essentialsSources`); unknown stays unknown and never shows in the app.',
    '',
    '| Festival | Id | Entry age | Camping | Official tickets |',
    '|---|---|---|---|---|',
    ...ess.map(r => `| ${r.name} | \`${r.id}\` | ${r.age} | ${r.camp} | ${r.tix} |`),
  ];
}

const doc = readFileSync(DOC, 'utf8');
const i = doc.indexOf(BEGIN), j = doc.indexOf(END);
if (i < 0 || j < i) {
  console.error(`[festival-status] ${path.relative(root, DOC)} has no festival-status markers`);
  process.exit(1);
}
const next = doc.slice(0, i) + block + doc.slice(j + END.length);
if (CHECK) {
  if (next !== doc) {
    console.error(`[festival-status] STALE: the queue's table no longer matches the registry (${live.length} live, ${gated.length} gated). Run: node scripts/festival-status.mjs`);
    process.exit(1);
  }
  console.log(`[festival-status] current: ${rows.length} entries, ${live.length} live, ${gated.length} gated`);
} else {
  writeFileSync(DOC, next);
  console.log(`[festival-status] wrote ${path.relative(root, DOC)}: ${rows.length} entries, ${live.length} live, ${gated.length} gated`);
}
